# Generated by Django 5.1 on 2025-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("card_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=150)),
                ("produced_at", models.CharField(max_length=100)),
                ("expired_on", models.CharField(max_length=100)),
                ("product_number", models.IntegerField()),
            ],
        ),
    ]
