# Generated by Django 5.1.7 on 2025-03-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoke', '0002_product_last_consumed_at_product_restock_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoledProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('sold_number', models.IntegerField(default=0)),
            ],
        ),
    ]
